apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{Name}#
  namespace: #{NameSpace}#
spec:
  replicas: #{Replicas}#
  selector:
    matchLabels:
      name: #{Name}#
  template:
    metadata:
      labels:
        app: #{Name}#
        name: #{Name}#
    spec:
      containers:
        - name: #{Name}#
          image: #{ContainerRegistry}#.azurecr.io/#{Name}#:#{Build.BuildNumber}#
          resources:
            limits:
              cpu: #{CpuPods}#
              memory: #{MemoriaPods}#
          env:
            - name: clientid
              valueFrom:
                secretKeyRef:
                  name: kv-secret
                  key: client_id
            - name: clientsecret
              valueFrom:
                secretKeyRef:
                  name: kv-secret
                  key: client_secret
            - name: keyvaulturl
              valueFrom:
                secretKeyRef:
                  name: kv-secret
                  key: keyvault_url
          ports:
            - containerPort: 80
            - containerPort: 50051
      imagePullSecrets:
        - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: #{Name}#
  namespace: #{NameSpace}#
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  loadBalancerIP: #{ServiceIP}#
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: #{Name}#
